In [2]:
import torch

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [4]:
print(torch.__version__)

1.12.1


# Introduction to PyTorch Tensors

# Creating Tensors

In [5]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#Get tensor back as Python int
scalar.item()

7

In [8]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
TENSOR[0,1]

tensor([4, 5, 6])

In [21]:
TENSOR[0,2,0]

tensor(7)

In [22]:
TENSOR = torch.tensor([[[[1,2,3],[4,5,6],[7,8,9]]],[[[10,11,12],[13,14,15],[16,17,18]]]])
TENSOR

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]]],


        [[[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]])

In [23]:
TENSOR.ndim

4

In [24]:
TENSOR.shape

torch.Size([2, 1, 3, 3])

In [25]:
TENSOR[1]
#3 sets of square brackets

tensor([[[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [26]:
TENSOR[1,0]
#2 sets of square brackets

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [27]:
TENSOR[1,0,1]
#1 set of square brackets

tensor([13, 14, 15])

In [28]:
TENSOR[1,0,1,2]
#No square brackets (scalar)

tensor(15)

# Creating Random Tensors in PyTorch

In [29]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2529, 0.5421, 0.7290, 0.3667],
        [0.6138, 0.8184, 0.2894, 0.0709],
        [0.5791, 0.2525, 0.3949, 0.5173]])

In [30]:
random_tensor.ndim

2

In [31]:
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,color channels(RGB)
random_image_size_tensor

tensor([[[0.2456, 0.9323, 0.8200],
         [0.1271, 0.8187, 0.9719],
         [0.9754, 0.5560, 0.2112],
         ...,
         [0.2051, 0.6015, 0.7365],
         [0.7834, 0.2099, 0.9551],
         [0.3808, 0.5078, 0.8090]],

        [[0.9713, 0.7376, 0.9352],
         [0.5230, 0.8038, 0.8025],
         [0.2146, 0.3833, 0.8348],
         ...,
         [0.2363, 0.5748, 0.9587],
         [0.7618, 0.9325, 0.6859],
         [0.3696, 0.1900, 0.4857]],

        [[0.2152, 0.2239, 0.5257],
         [0.8437, 0.2566, 0.7787],
         [0.0067, 0.3890, 0.5080],
         ...,
         [0.7191, 0.9244, 0.7484],
         [0.6606, 0.2635, 0.2962],
         [0.0457, 0.5802, 0.9869]],

        ...,

        [[0.0098, 0.9445, 0.0904],
         [0.5872, 0.0860, 0.7133],
         [0.2230, 0.7777, 0.3608],
         ...,
         [0.3216, 0.1623, 0.4390],
         [0.1976, 0.3764, 0.1714],
         [0.1166, 0.0828, 0.9859]],

        [[0.2924, 0.1591, 0.7317],
         [0.8972, 0.9404, 0.7328],
         [0.

In [32]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [33]:
random_image_size_tensor.ndim

3

# Creating Tensors with Zeros and Ones in PyTorch

In [34]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
ones.dtype

torch.float32

# Creating a Tensor Range and Tensors Like Other Tensors

In [37]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
one_to_ten = torch.arange(start=0,end=1,step=0.0001) #default step size is 1
one_to_ten

tensor([0.0000e+00, 1.0000e-04, 2.0000e-04,  ..., 9.9970e-01, 9.9980e-01,
        9.9990e-01])

In [39]:
one_to_ten_zeros = torch.zeros_like(input=one_to_ten)
one_to_ten_zeros

tensor([0., 0., 0.,  ..., 0., 0., 0.])

In [40]:
one_to_ten_zeros.ndim

1

In [41]:
one_to_ten_zeros.shape

torch.Size([10000])

In [42]:
one_to_ten.ndim

1

In [43]:
one_to_ten.shape

torch.Size([10000])

# Dealing With Tensor Data Types

In [44]:
#Float 32 Tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None) #default dtype is float32
float_32_tensor

tensor([3., 6., 9.])

In [45]:
float_32_tensor.dtype

torch.float32

In [46]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #datatype
                               device=None, #What device is tensor on (GPU, CPU, cuda)
                               requires_grad=False) #does PyTorch track the gradients

In [47]:
#change datatype of a tensor with .type()
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

# Getting Tensor Attributes

In [48]:
print(float_32_tensor)
print(f"Datatype of Tensor: {float_32_tensor.dtype}")
print(f"Shape of Tensor: {float_32_tensor.shape}")
print(f"Device of Tensor: {float_32_tensor.device}")

tensor([3., 6., 9.])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3])
Device of Tensor: cpu


In [49]:
print(one_to_ten)
print(f"Datatype of Tensor: {one_to_ten.dtype}")
print(f"Shape of Tensor: {one_to_ten.shape}")
print(f"Device of Tensor: {one_to_ten.device}")

tensor([0.0000e+00, 1.0000e-04, 2.0000e-04,  ..., 9.9970e-01, 9.9980e-01,
        9.9990e-01])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([10000])
Device of Tensor: cpu


# Manipulating Tensors (Tensor Operations)

In [50]:
tensor = torch.tensor([1,2,3])
#addition
tensor + 10

tensor([11, 12, 13])

In [51]:
#multiplication
tensor * 10

tensor([10, 20, 30])

In [52]:
#subtraction
tensor - 10

tensor([-9, -8, -7])

In [53]:
#division
tensor/2

tensor([0.5000, 1.0000, 1.5000])

In [54]:
#PyTorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [55]:
torch.add(tensor,10)

tensor([11, 12, 13])

# Matrix Multiplication (Part 1)

In [56]:
#Matrix multiplication <=> Dot product
# The @ symbol can be used to perform matrix multiplication

In [57]:
tensor

tensor([1, 2, 3])

In [58]:
#element-wise
tensor * tensor

tensor([1, 4, 9])

In [59]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [60]:
tensor @ tensor

tensor(14)

# Matrix Multiplication (Part 2): Two Main Rules

In [61]:
#1. Inner dimensions must match (number of columns of first matrix = number of rows of 2nd matrix)
#ex: 3x4 multiplied by a 4x1 is okay
#ex: 3x4 multiplied by a 3x4 is not okay

In [62]:
#2. The resulting matrix will be the outer dimensions
#ex: 3x4 multiplied by a 4x1 results in a 3x1 matrix
#ex: 5x8 multiplied by a 8x2 results in a 5x2 matrix

# Matrix Multiplication (Part 3): Dealing With Tensor Shape Errors

In [63]:
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensorB = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

In [64]:
torch.mm(tensorA.T,tensorB) #torch.mm is the same as torch.matmul

tensor([[ 76, 103],
        [100, 136]])

In [65]:
#Transpose operation

In [66]:
tensorA

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [67]:
tensorA.T

tensor([[1, 3, 5],
        [2, 4, 6]])

# Finding the Min, Max, Mean, & Sum of Tensors (Tensor Aggregation)

In [68]:
tensor = torch.rand(size=(5,5))
tensor

tensor([[0.2676, 0.5802, 0.2697, 0.1070, 0.3050],
        [0.2881, 0.7149, 0.1844, 0.8904, 0.1011],
        [0.1043, 0.2481, 0.2268, 0.1154, 0.3373],
        [0.7565, 0.6117, 0.6652, 0.6936, 0.5134],
        [0.9727, 0.8119, 0.4073, 0.6839, 0.1439]])

In [69]:
#min
torch.min(tensor) #also can use tensor.min()

tensor(0.1011)

In [70]:
#max
torch.max(tensor) #also can use tensor.max()

tensor(0.9727)

In [71]:
#mean
torch.mean(tensor) #also can use tensor.mean()
#torch.mean cannot work with datatypes long/int64 (integers)

tensor(0.4400)

In [72]:
#sum
torch.sum(tensor) #also can use tensor.sum()

tensor(11.0004)

# Finding the Positional Min and Max of Tensors (argmin and argmax)

In [73]:
tensor

tensor([[0.2676, 0.5802, 0.2697, 0.1070, 0.3050],
        [0.2881, 0.7149, 0.1844, 0.8904, 0.1011],
        [0.1043, 0.2481, 0.2268, 0.1154, 0.3373],
        [0.7565, 0.6117, 0.6652, 0.6936, 0.5134],
        [0.9727, 0.8119, 0.4073, 0.6839, 0.1439]])

In [74]:
tensor.argmin(), tensor.min()

(tensor(9), tensor(0.1011))

In [75]:
tensor.argmax(), tensor.max()

(tensor(20), tensor(0.9727))

# Reshaping, Viewing, & Stacking Tensors

In [76]:
#Reshaping reshapes an input tensor to a defined shape
#Viewing returns a view of an input tensor of certain shape but keep the same memory as the original tensor
#Stacking combines multiple tensors on top of each other (vstack) or side-by-side (hstack)
#Squeezing removes all '1' dimensions from a tensor
#Unsqueezing adds a '1' dimension to a target tensor
#Permuting returns a view of the input with dimensions permuted in a certain way

In [77]:
tensor = torch.rand(size=(3,4))
tensor, tensor.shape

(tensor([[0.6115, 0.4119, 0.0997, 0.0065],
         [0.3551, 0.3265, 0.3202, 0.8197],
         [0.8802, 0.2977, 0.4559, 0.0910]]),
 torch.Size([3, 4]))

In [78]:
#Add an extra dimension
tensor_reshaped = tensor.reshape(2,6)
tensor_reshaped, tensor_reshaped.shape

(tensor([[0.6115, 0.4119, 0.0997, 0.0065, 0.3551, 0.3265],
         [0.3202, 0.8197, 0.8802, 0.2977, 0.4559, 0.0910]]),
 torch.Size([2, 6]))

In [79]:
#Change the view
tensor_view = tensor.view(6,2)
tensor_view

tensor([[0.6115, 0.4119],
        [0.0997, 0.0065],
        [0.3551, 0.3265],
        [0.3202, 0.8197],
        [0.8802, 0.2977],
        [0.4559, 0.0910]])

In [80]:
#Changing tensor_view changes tensor, because a view of a tensor shares the same memory as the original input

In [81]:
tensor_view[0][0] = 0.001
tensor_view, tensor #Note the first element of tensor_view and tensor is now 0.0010

(tensor([[0.0010, 0.4119],
         [0.0997, 0.0065],
         [0.3551, 0.3265],
         [0.3202, 0.8197],
         [0.8802, 0.2977],
         [0.4559, 0.0910]]),
 tensor([[0.0010, 0.4119, 0.0997, 0.0065],
         [0.3551, 0.3265, 0.3202, 0.8197],
         [0.8802, 0.2977, 0.4559, 0.0910]]))

In [82]:
#Stack tensors on top of each other
tensor_stacked = torch.stack([tensor,tensor,tensor,tensor],dim=0) #dim=0 by default
tensor_stacked

tensor([[[0.0010, 0.4119, 0.0997, 0.0065],
         [0.3551, 0.3265, 0.3202, 0.8197],
         [0.8802, 0.2977, 0.4559, 0.0910]],

        [[0.0010, 0.4119, 0.0997, 0.0065],
         [0.3551, 0.3265, 0.3202, 0.8197],
         [0.8802, 0.2977, 0.4559, 0.0910]],

        [[0.0010, 0.4119, 0.0997, 0.0065],
         [0.3551, 0.3265, 0.3202, 0.8197],
         [0.8802, 0.2977, 0.4559, 0.0910]],

        [[0.0010, 0.4119, 0.0997, 0.0065],
         [0.3551, 0.3265, 0.3202, 0.8197],
         [0.8802, 0.2977, 0.4559, 0.0910]]])

In [83]:
tensor_stacked = torch.stack([tensor,tensor,tensor,tensor],dim=1)
tensor_stacked

tensor([[[0.0010, 0.4119, 0.0997, 0.0065],
         [0.0010, 0.4119, 0.0997, 0.0065],
         [0.0010, 0.4119, 0.0997, 0.0065],
         [0.0010, 0.4119, 0.0997, 0.0065]],

        [[0.3551, 0.3265, 0.3202, 0.8197],
         [0.3551, 0.3265, 0.3202, 0.8197],
         [0.3551, 0.3265, 0.3202, 0.8197],
         [0.3551, 0.3265, 0.3202, 0.8197]],

        [[0.8802, 0.2977, 0.4559, 0.0910],
         [0.8802, 0.2977, 0.4559, 0.0910],
         [0.8802, 0.2977, 0.4559, 0.0910],
         [0.8802, 0.2977, 0.4559, 0.0910]]])

In [84]:
tensor_stacked = torch.stack([tensor,tensor,tensor,tensor],dim=2)
tensor_stacked

tensor([[[0.0010, 0.0010, 0.0010, 0.0010],
         [0.4119, 0.4119, 0.4119, 0.4119],
         [0.0997, 0.0997, 0.0997, 0.0997],
         [0.0065, 0.0065, 0.0065, 0.0065]],

        [[0.3551, 0.3551, 0.3551, 0.3551],
         [0.3265, 0.3265, 0.3265, 0.3265],
         [0.3202, 0.3202, 0.3202, 0.3202],
         [0.8197, 0.8197, 0.8197, 0.8197]],

        [[0.8802, 0.8802, 0.8802, 0.8802],
         [0.2977, 0.2977, 0.2977, 0.2977],
         [0.4559, 0.4559, 0.4559, 0.4559],
         [0.0910, 0.0910, 0.0910, 0.0910]]])

# Squeezing, Unsqueezing, & Permuting Tensors

In [85]:
new_tensor = torch.rand(1,12)
new_tensor, new_tensor.shape

(tensor([[0.9048, 0.3940, 0.8545, 0.0291, 0.2634, 0.3782, 0.9366, 0.3362, 0.8466,
          0.4876, 0.4433, 0.1516]]),
 torch.Size([1, 12]))

In [86]:
#Squeeze function
squeezed_tensor = new_tensor.squeeze()
squeezed_tensor #Note there is now only one set of brackets []

tensor([0.9048, 0.3940, 0.8545, 0.0291, 0.2634, 0.3782, 0.9366, 0.3362, 0.8466,
        0.4876, 0.4433, 0.1516])

In [87]:
squeezed_tensor.shape

torch.Size([12])

In [88]:
#Unsqueeze function
unsqueezed_tensor = squeezed_tensor.unsqueeze(dim=0)
unsqueezed_tensor

tensor([[0.9048, 0.3940, 0.8545, 0.0291, 0.2634, 0.3782, 0.9366, 0.3362, 0.8466,
         0.4876, 0.4433, 0.1516]])

In [89]:
unsqueezed_tensor.shape

torch.Size([1, 12])

In [90]:
squeezed_tensor.unsqueeze(dim=1)

tensor([[0.9048],
        [0.3940],
        [0.8545],
        [0.0291],
        [0.2634],
        [0.3782],
        [0.9366],
        [0.3362],
        [0.8466],
        [0.4876],
        [0.4433],
        [0.1516]])

In [91]:
squeezed_tensor.unsqueeze(dim=1).shape

torch.Size([12, 1])

In [92]:
#Permute function
image_tensor = torch.rand(size=(224,224,3)) #height, width, color channels

In [93]:
image_tensor.shape

torch.Size([224, 224, 3])

In [94]:
image_permuted = image_tensor.permute(2,0,1)

In [95]:
image_permuted.shape

torch.Size([3, 224, 224])

# Selecting Data From Tensors (Indexing)

In [96]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [97]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [98]:
x[0][0], x[0,0] #both are equivalent

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [99]:
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [100]:
#You can use : to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [101]:
x[:,:,1]

tensor([[2, 5, 8]])

In [102]:
x[:,1,:]

tensor([[4, 5, 6]])

In [103]:
x[:,:,2]

tensor([[3, 6, 9]])

# PyTorch Tensors & Numpy

In [104]:
#You can change data in NumPy to PyTorch tensor (torch.from_numpy(ndarray))
#You can also change PyTorch tensor to NumPy (torch.Tensor.numpy())

In [105]:
#NumPy array to tensor
array = np.arange(1.0,8.0) #default dtype for NumPy array is float64
tensor = torch.from_numpy(array) #default dtype for tensor is float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [106]:
#tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# PyTorch Reproducability (Taking the Random out of Random)

In [107]:
#we can use a random seed here to reproduce results

In [108]:
RandA = torch.rand(3,4)
RandB = torch.rand(3,4)

In [109]:
RandA, RandB, RandA == RandB

(tensor([[0.4970, 0.3740, 0.9690, 0.4341],
         [0.3365, 0.1118, 0.1751, 0.0538],
         [0.0552, 0.0833, 0.7495, 0.7264]]),
 tensor([[0.4268, 0.4484, 0.4574, 0.0539],
         [0.7210, 0.5344, 0.0615, 0.4177],
         [0.2234, 0.1173, 0.7687, 0.9477]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [110]:
#Set the random seed
torch.manual_seed(420)
RandC = torch.rand(3,4)
torch.manual_seed(420)
RandD = torch.rand(3,4)

In [111]:
RandC, RandD, RandC == RandD

(tensor([[0.8054, 0.1990, 0.9759, 0.1028],
         [0.3475, 0.1554, 0.8856, 0.6876],
         [0.2506, 0.1133, 0.2105, 0.4035]]),
 tensor([[0.8054, 0.1990, 0.9759, 0.1028],
         [0.3475, 0.1554, 0.8856, 0.6876],
         [0.2506, 0.1133, 0.2105, 0.4035]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

# Different Ways of Accessing a GPU in PyTorch

In [112]:
#GPUs = faster computations thanks to CUDA, NVIDIA hardware, and PyTorch under the hood processes

In [113]:
#Options are use Google Colab which allows access to GPUs, purchase your own GPU, or use Cloud computing (GCP, AWS, Azure)

In [114]:
#Check for GPU access with PyTorch
torch.cuda.is_available()

False

In [115]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [116]:
#Count number of devices(GPUs)
torch.cuda.device_count()

0

# Setting Up Device-Agnostic Code & Putting Tensors On & Off the GPU

In [118]:
#Putting tensors and models on the GPU
tensor = torch.tensor([1,2,3]) #default is on the CPU
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [121]:
#Move tensor to GPU if available
tensor_GPU = tensor.to(device) #device object defined above
tensor_GPU, tensor_GPU.device

(tensor([1, 2, 3]), device(type='cpu'))

In [122]:
#The above code will run error-free whether or not there is a GPU available (device-agnostic)

In [123]:
#NumPy only works with the CPU
#Move tensors from GPU to CPU
tensor_GPU.numpy() #will get error if tensor object is on the GPU

array([1, 2, 3], dtype=int64)

In [125]:
tensor_GPU.cpu() # copies tensor to the CPU

tensor([1, 2, 3])

# Exercises and Extra-Curriculum

In [128]:
#2.
tensor1 = torch.rand(size=(7,7))
tensor1

tensor([[0.9659, 0.9114, 0.3016, 0.3314, 0.8997, 0.3720, 0.4452],
        [0.4736, 0.0931, 0.9430, 0.4508, 0.9885, 0.9117, 0.7173],
        [0.4887, 0.4945, 0.5115, 0.0140, 0.3807, 0.2687, 0.4703],
        [0.5612, 0.1082, 0.8800, 0.9083, 0.8110, 0.7245, 0.5791],
        [0.1397, 0.7014, 0.6772, 0.9833, 0.0285, 0.9340, 0.8926],
        [0.5927, 0.6665, 0.5598, 0.4600, 0.6007, 0.7895, 0.5570],
        [0.4546, 0.4835, 0.1149, 0.2606, 0.9070, 0.5295, 0.5525]])

In [129]:
#3.
tensor2 = torch.rand(size=(1,7))
tensor2

tensor([[0.0625, 0.8653, 0.5179, 0.4332, 0.0107, 0.8012, 0.4354]])

In [130]:
torch.mm(tensor2,tensor1)

tensor([[1.6406, 1.1925, 1.9867, 1.3040, 2.3365, 2.1382, 1.8392]])

In [131]:
torch.mm(tensor1,tensor2.T)

tensor([[1.6503],
        [1.8472],
        [1.1535],
        [1.8192],
        [2.5296],
        [1.9845],
        [1.2936]])

In [132]:
#4.
torch.manual_seed(0)
tensor1 = torch.rand(size=(7,7))
torch.manual_seed(0)
tensor2 = torch.rand(size=(1,7))
tensor1,tensor2

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]))

In [133]:
torch.mm(tensor2,tensor1)

tensor([[1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752]])

In [134]:
torch.mm(tensor1,tensor2.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [136]:
#5.
#To set the random seed on the GPU, use set_rng_state
#Note that this function is only available on PyTorch 2

In [138]:
#6.
torch.manual_seed(1234)
tensor1 = torch.rand(size=(2,3))
torch.manual_seed(1234)
tensor2 = torch.rand(size=(2,3))
tensor1_GPU = tensor1.to(device) 
tensor2_GPU = tensor2.to(device)

In [139]:
#7.
torch.mm(tensor1_GPU, tensor2_GPU.T)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

In [142]:
output = torch.mm(tensor1_GPU.T, tensor2_GPU)
output

tensor([[0.1353, 0.0330, 0.2644],
        [0.0330, 0.1649, 0.1453],
        [0.2644, 0.1453, 0.5584]])

In [145]:
#8.
torch.max(output)

tensor(0.5584)

In [146]:
torch.min(output)

tensor(0.0330)

In [147]:
#9.
torch.argmax(output)

tensor(8)

In [148]:
torch.argmin(output)

tensor(1)

In [153]:
#10.
torch.manual_seed(7)
rand_tensor = torch.rand(size=(1,1,1,10))
rand_tensor_squeezed = torch.squeeze(rand_tensor)
print(f"Original tensor is {rand_tensor} with shape {rand_tensor.shape}")
print(f"\n")
print(f"Squeezed tensor is {rand_tensor_squeezed} with shape {rand_tensor_squeezed.shape}")

Original tensor is tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) with shape torch.Size([1, 1, 1, 10])


Squeezed tensor is tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) with shape torch.Size([10])
